# Generated by Django 4.2.17 on 2025-01-18 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_category_subscribers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcategory',
            unique_together={('post', 'category')},
        ),
    ]
